title: CV
destination: docs
# baseurl: ""
baseurl: "/CV"
url: ""
collections_dir: collections
collections: [ passions, personalSkills, speakingLanguages, favoriteMovies, favoriteGames, projects ]

exclude: [ _assets, node_modules, Gemfile, Gemfile.lock, gulpFile.js, package.json, package-lock.json, README.md ]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
